name: "dbt Cloud action"
description: "Runs a dbt Cloud Job specified by Job ID"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  dbt_cloud_token:
    description: "dbt Cloud API token"
    required: true
  dbt_cloud_account_id:
    description: "dbt Cloud account ID"
    required: true
  dbt_cloud_job_id:
    description: "dbt Cloud Job ID"
    required: true
  cause:
    description: "Job trigger cause"
    required: true
    default: "Triggered by a GitHub Action"
  failure_on_error:
    description: Boolean to make the action report a failure when dbt-cloud runs. Mark this as `false` to run fal after the dbt-cloud job.
    required: true
  git_sha:
    description: "The git SHA to execute dbt Cloud Job"
    required: false
  interval:
    description: "Interval between polls in seconds"
    required: false
    default: "30"
outputs:
  git_sha:
    description: "Repository SHA in which dbt Cloud Job ran"
runs:
  using: "node12"
  main: "index.js"
