name: "dbt Cloud action"
description: "Runs a dbt Cloud job specified by job id"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  dbt_cloud_token:
    description: "dbt Cloud api token"
    required: true
  dbt_cloud_account_id:
    description: "dbt Cloud account id"
    required: true
  dbt_cloud_job_id:
    description: "dbt Cloud job id"
    required: true
  cause:
    description: "Job trigger cause"
    required: true
    default: "Triggered by a GitHub Action"
  steps_override:
    description: "List of steps to override the jobs default steps"
    required: false
  interval:
    description: "Interval between polls in seconds"
    required: false
    default: "30"
runs:
  using: "node12"
  main: "index.js"
